### PR TITLE
Fix evaluation of variable-length edges in expression ordering

### LINKED ISSUE #2005: Building match op tree fails in path with cycle and variable-length traversal
Running the query:
```
MATCH (n2)<-[*]-(n:L {v: 5})<--(n) WHERE n2.v = 10 RETURN n
```
Triggers the assertion failure:
```
build_match_op_tree.c:61 'AlgebraicExpression_DiagonalOperand(ae_src, 0)' is not true  
```

### PR DESCRIPTION
**Pull request by jeffreylovitz**
Resolves #2005 and enables LDBC test interactive-complex-11.

### CODE REVIEW

File: src/execution_plan/optimizations/traverse_order_utils.c [hunk 1]
```diff
@@ -17,10 +17,6 @@ static bool _AlgebraicExpression_IsVarLen
 	ASSERT(qg  != NULL);
 	ASSERT(exp != NULL);
 
-	// variable length expression contains a single edge operand
-	if(AlgebraicExpression_OperandCount(exp) != 1  ||
-	   AlgebraicExpression_OperationCount(exp, AL_EXP_ALL) > 0) return false;
-
```
Comment (swilly22) [inline src/execution_plan/optimizations/traverse_order_utils.c:23]: Can you please explain why was this condition removed ?

Comment (jeffreylovitz) [reply src/execution_plan/optimizations/traverse_order_utils.c:23]: Because we can validly have transpose and addition ops here, and in the case of addition we may have multiple operands. The following query causes a transposed traversal of one operand:
```
MATCH (b)<-[*]-(a:L {v: 5})<--(a) WHERE b.v = 10 RETURN a
```
And this bidirectional traversal will create `E + T(E)`:
```
 MATCH (a:L {v: 5})-[E*]-(b:L) WHERE a <> b RETURN b
```
Traversing multiple label types would also build an addition of N operands.

Comment (swilly22) [reply src/execution_plan/optimizations/traverse_order_utils.c:23]: 👍 thank you!

**Review by swilly22 — APPROVED** [review]
@jeffreylovitz please cherry-pick to 2.4

**Comment by swilly22** [comment]
@jeffreylovitz was interactive-complex-11 enabled ?
