### PR TITLE
removed RedisModule_ReplyWithError from ast validations

### LINKED ISSUE #1155: Switch from RedisModule_ReplyWithError to QueryCtx_SetError
```
GRAPH.QUERY g "CYPHER props={a:1,b:2} CREATE (a:A $props)"
(error) Encountered unhandled type in inlined properties.

PING
(error) RedisGraph does not currently support the type 'map'
```

This is due to multiple error reporting by the first query, we need to avoid calling `RedisModule_ReplyWithError` from within `ast_validations.c` and use `QueryCtx_SetError` instead.

Currently running `make test` on my machine fails, i'm not sure how circle is passing...

### PR DESCRIPTION
**Pull request by DvirDukhan**
closes #1155

### CODE REVIEW

File: src/ast/ast_validations.c [hunk 1]
```diff
@@ -1659,17 +1655,19 @@ static AST_Validation _AST_ValidateUnionQuery(AST *mock_ast, char **reason) {
 	return res;
 }
 
-AST_Validation AST_Validate_Query(RedisModuleCtx *ctx, const cypher_parse_result_t *result) {
-	if(_AST_Validate_ParseResultRoot(ctx, result) != AST_VALID) return AST_INVALID;
+AST_Validation AST_Validate_Query(const cypher_parse_result_t *result) {
+	char *err = NULL;
+	if(_AST_Validate_ParseResultRoot(result, &err) != AST_VALID) {
+		QueryCtx_SetError(err);
```
Comment (swilly22) [inline src/ast/ast_validations.c:1661]: Wouldn't you prefer not to pass `err` and call `QueryCtx_SetError` wherever the error is detected?

Comment (jeffreylovitz) [reply src/ast/ast_validations.c:1661]: I agree with this, we have `QueryCtx_SetError` so that we don't need to store these `char **`s - we should write errors into the context upon encountering them.

Other than that, this PR looks good to me!
