### PR TITLE
Tuple iter race

### LINKED ISSUE #1785: Crash on `Path_Free`: variable_length_filter benchmark
Raised due to CI benchmarks: https://app.circleci.com/pipelines/github/RedisGraph/RedisGraph/3289/workflows/bb9676f9-decc-4fba-95c3-0e6b072863c9/jobs/11960

This crash happens spuriously ( not always ) but we should be able to crash RG at least once using the following remote benchmark command:

```
make benchmark BENCHMARK=variable_length_filter.yml REMOTE=1 BENCHMARK_REPETITIONS=10 PUSH_S3=1
``` 
redis logfile:
```
cat /tmp/VARIABLE-LENGTH-FILTER_2021-06-20-18-18-14.log.log 
4527:C 20 Jun 2021 18:18:33.952 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
4527:C 20 Jun 2021 18:18:33.952 # Redis version=6.0.10, bits=64, commit=8d70d498, modified=0, pid=4527, just started
4527:C 20 Jun 2021 18:18:33.952 # Configuration loaded
4527:M 20 Jun 2021 18:18:33.953 * Increased maximum number of open files to 10032 (it was originally set to 1024).
4527:M 20 Jun 2021 18:18:33.953 * Running mode=standalone, port=6379.
4527:M 20 Jun 2021 18:18:33.953 # Server initialized
4527:M 20 Jun 2021 18:18:33.953 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
4527:M 20 Jun 2021 18:18:33.955 * <graph> Starting up RedisGraph version 99.99.99.
4527:M 20 Jun 2021 18:18:33.956 * <graph> Thread pool created, using 32 threads.
4527:M 20 Jun 2021 18:18:33.956 * <graph> Maximum number of OpenMP threads set to 32
4527:M 20 Jun 2021 18:18:33.956 * Module 'graph' loaded from /tmp/module.so
4527:M 20 Jun 2021 18:18:33.957 * Loading RDB produced by version 6.2.1
4527:M 20 Jun 2021 18:18:33.957 * RDB age 6404258 seconds
4527:M 20 Jun 2021 18:18:33.957 * RDB memory usage when created 1.52 Mb
4527:M 20 Jun 2021 18:18:33.957 * <graph> Done decoding graph g
4527:M 20 Jun 2021 18:18:33.957 * <module> Deleted 0 virtual keys for graph g
4527:M 20 Jun 2021 18:18:33.957 * DB loaded from disk: 0.000 seconds
4527:M 20 Jun 2021 18:18:33.957 * Ready to accept connections


=== REDIS BUG REPORT START: Cut & paste starting from here ===
4527:M 20 Jun 2021 18:18:41.956 # Redis 6.0.10 crashed by signal: 11, si_code: 1
4527:M 20 Jun 2021 18:18:41.956 # Crashed running the instruction at: 0x55798fcbae39
4527:M 20 Jun 2021 18:18:41.956 # Accessing address: (nil)
4527:M 20 Jun 2021 18:18:41.956 # Killed by PID: 0, UID: 0
4527:M 20 Jun 2021 18:18:41.956 # Failed assertion: <no assertion failed> (<no file>:0)

------ STACK TRACE ------
EIP:
redis-server *:6379(je_large_dalloc+0x29)[0x55798fcbae39]

Backtrace:
redis-server *:6379(logStackTrace+0x5a)[0x55798fbfb34a]
redis-server *:6379(sigsegvHandler+0xd5)[0x55798fbfbb45]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12980)[0x7fcde747b980]
redis-server *:6379(je_large_dalloc+0x29)[0x55798fcbae39]
/tmp/module.so(Path_Free+0x35)[0x7fcde5268115]
/tmp/module.so(Record_FreeEntries+0x60)[0x7fcde526bfb0]
/tmp/module.so(ObjectPool_DeleteItem+0x1b)[0x7fcde52aa9cb]
/tmp/module.so(+0x1cbc6f)[0x7fcde5275c6f]
/tmp/module.so(+0x1cb44c)[0x7fcde527544c]
/tmp/module.so(ExecutionPlan_Execute+0x60)[0x7fcde526b220]
/tmp/module.so(+0x1bac1e)[0x7fcde5264c1e]
/tmp/module.so(+0x200c84)[0x7fcde52aac84]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76db)[0x7fcde74706db]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7fcde719971f]

------ INFO OUTPUT ------
# Server
redis_version:6.0.10
redis_git_sha1:8d70d498
redis_git_dirty:0
redis_build_id:de19b04611ba43b
redis_mode:standalone
os:Linux 5.4.0-1029-aws x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:7.5.0
process_id:4527
run_id:2e679c982e3461c124e2c8577d681ff9848abe23
tcp_port:6379
uptime_in_seconds:8
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:13600385
executable:/home/ubuntu/redis-server
config_file:
io_threads_active:0

# Clients
connected_clients:33
client_recent_max_input_buffer:8
client_recent_max_output_buffer:0
blocked_clients:19
tracking_clients:0
clients_in_timeout_table:0

# Memory
used_memory:6310944
used_memory_human:6.02M
used_memory_rss:10330112
used_memory_rss_human:9.85M
used_memory_peak:9828480
used_memory_peak_human:9.37M
used_memory_peak_perc:64.44%
used_memory_overhead:837272
used_memory_startup:837168
used_memory_dataset:5496320
used_memory_dataset_perc:100.00%
allocator_allocated:1912120
allocator_active:2105344
allocator_resident:6758400
total_system_memory:267328163840
total_system_memory_human:248.97G
used_memory_lua:37888
used_memory_lua_human:37.00K
used_memory_scripts:0
used_memory_scripts_human:0B
number_of_cached_scripts:0
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
allocator_frag_ratio:1.10
allocator_frag_bytes:193224
allocator_rss_ratio:3.21
allocator_rss_bytes:4653056
rss_overhead_ratio:1.53
rss_overhead_bytes:3571712
mem_fragmentation_ratio:6.15
mem_fragmentation_bytes:8650048
mem_not_counted_for_evict:0
mem_replication_backlog:0
mem_clients_slaves:0
mem_clients_normal:0
mem_aof_buffer:0
mem_allocator:jemalloc-5.1.0
active_defrag_running:0
lazyfree_pending_objects:0

# Persistence
loading:0
rdb_changes_since_last_save:0
rdb_bgsave_in_progress:0
rdb_last_save_time:1624213113
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:0
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0
module_fork_in_progress:0
module_fork_last_cow_size:0

# Stats
total_connections_received:34
total_commands_processed:496
instantaneous_ops_per_sec:0
total_net_input_bytes:72434
total_net_output_bytes:143445
instantaneous_input_kbps:0.00
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
expire_cycle_cpu_milliseconds:0
evicted_keys:0
keyspace_hits:494
keyspace_misses:0
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0
tracking_total_keys:0
tracking_total_items:0
tracking_total_prefixes:0
unexpected_error_replies:0
total_reads_processed:498
total_writes_processed:476
io_threaded_reads_processed:0
io_threaded_writes_processed:0

# Replication
role:master
connected_slaves:0
master_replid:682df2e11f4b0eafc7b1c216687fd4c41f70255d
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:0.075287
used_cpu_user:0.068443
used_cpu_sys_children:0.000000
used_cpu_user_children:0.000000

# Modules
module:name=graph,ver=999999,api=1,filters=0,usedby=[],using=[],options=[]

# Commandstats
cmdstat_ping:calls=1,usec=0,usec_per_call=0.00
cmdstat_info:calls=1,usec=16,usec_per_call=16.00
cmdstat_module:calls=1,usec=3,usec_per_call=3.00
cmdstat_graph.QUERY:calls=494,usec=8141,usec_per_call=16.48

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=1,expires=0,avg_ttl=0

------ CLIENT LIST OUTPUT ------
id=8 addr=10.3.0.63:39560 fd=10 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=61456 events=r cmd=module user=default
id=9 addr=10.3.0.63:39562 fd=11 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 argv-mem=0 obl=243 oll=0 omem=0 tot-mem=61472 events=r cmd=graph.QUERY user=default
id=11 addr=10.3.0.63:39564 fd=12 name= age=0 idle=0 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 argv-mem=86 obl=0 oll=0 omem=0 tot-mem=61558 events=r cmd=graph.QUERY user=default
id=14 addr=10.3.0.63:39566 fd=13 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=61472 events=r cmd=graph.QUERY user=default
id=17 addr=10.3.0.63:39568 fd=14 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=61472 events=r cmd=graph.QUERY user=default
id=20 addr=10.3.0.63:39570 fd=15 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=61472 events=r cmd=graph.QUERY user=default
id=23 addr=10.3.0.63:39572 fd=16 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=61472 events=r cmd=graph.QUERY user=default
id=27 addr=10.3.0.63:39574 fd=17 name= age=0 idle=0 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 argv-mem=107 obl=0 oll=0 omem=0 tot-mem=61579 events=r cmd=graph.QUERY user=default
id=29 addr=10.3.0.63:39576 fd=18 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=61472 events=r cmd=graph.QUERY user=default
id=32 addr=10.3.0.63:39578 fd=19 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=61472 events=r cmd=graph.QUERY user=default
id=40 addr=10.3.0.63:39580 fd=20 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=61472 events=r cmd=graph.QUERY user=default
id=44 addr=10.3.0.63:39582 fd=21 name= age=0 idle=0 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 argv-mem=86 obl=0 oll=0 omem=0 tot-mem=61558 events=r cmd=graph.QUERY user=default
id=46 addr=10.3.0.63:39584 fd=22 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=61472 events=r cmd=graph.QUERY user=default
id=52 addr=10.3.0.63:39586 fd=23 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=61472 events=r cmd=graph.QUERY user=default
id=55 addr=10.3.0.63:39588 fd=24 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=61472 events=r cmd=graph.QUERY user=default
id=58 addr=10.3.0.63:39590 fd=25 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=61472 events=r cmd=graph.QUERY user=default
id=61 addr=10.3.0.63:39592 fd=26 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=61472 events=r cmd=graph.QUERY user=default
id=64 addr=10.3.0.63:39594 fd=27 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=61472 events=r cmd=graph.QUERY user=default
id=69 addr=10.3.0.63:39596 fd=28 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=61472 events=r cmd=graph.QUERY user=default
id=73 addr=10.3.0.63:39598 fd=29 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=61472 events=r cmd=graph.QUERY user=default
id=77 addr=10.3.0.63:39600 fd=30 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=61472 events=r cmd=graph.QUERY user=default
id=79 addr=10.3.0.63:39602 fd=31 name= age=0 idle=0 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 argv-mem=107 obl=0 oll=0 omem=0 tot-mem=61579 events=r cmd=graph.QUERY user=default
id=80 addr=10.3.0.63:39604 fd=32 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=61472 events=r cmd=graph.QUERY user=default
id=81 addr=10.3.0.63:39606 fd=33 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=61472 events=r cmd=graph.QUERY user=default
id=90 addr=10.3.0.63:39608 fd=34 name= age=0 idle=0 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 argv-mem=149 obl=0 oll=0 omem=0 tot-mem=61621 events=r cmd=graph.QUERY user=default
id=91 addr=10.3.0.63:39610 fd=35 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=61472 events=r cmd=graph.QUERY user=default
id=92 addr=10.3.0.63:39612 fd=36 name= age=0 idle=0 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 argv-mem=86 obl=0 oll=0 omem=0 tot-mem=61558 events=r cmd=graph.QUERY user=default
id=93 addr=10.3.0.63:39614 fd=37 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=61472 events=r cmd=graph.QUERY user=default
id=103 addr=10.3.0.63:39616 fd=38 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=61472 events=r cmd=graph.QUERY user=default
id=104 addr=10.3.0.63:39618 fd=39 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=61472 events=r cmd=graph.QUERY user=default
id=105 addr=10.3.0.63:39620 fd=40 name= age=0 idle=0 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 argv-mem=128 obl=0 oll=0 omem=0 tot-mem=61600 events=r cmd=graph.QUERY user=default
id=125 addr=10.3.0.63:39622 fd=41 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=61472 events=r cmd=graph.QUERY user=default
id=126 addr=10.3.0.63:39624 fd=42 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=61472 events=r cmd=graph.QUERY user=default

------ CURRENT CLIENT INFO ------
id=23 addr=10.3.0.63:39572 fd=16 name= age=0 idle=0 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 argv-mem=107 obl=0 oll=0 omem=0 tot-mem=61579 events=r cmd=graph.QUERY user=default
argv[0]: 'GRAPH.QUERY'
argv[1]: 'g'
argv[2]: 'MATCH (a)-[e*]->(b) WHERE e.connects = "CD" OR e.connects = "DE" RETURN a.name, b.name'
argv[3]: '--compact'
4527:M 20 Jun 2021 18:18:41.960 # key 'g' found in DB containing the following object:
4527:M 20 Jun 2021 18:18:41.960 # Object type: 5
4527:M 20 Jun 2021 18:18:41.960 # Object encoding: 0
4527:M 20 Jun 2021 18:18:41.960 # Object refcount: 1

------ REGISTERS ------
4527:M 20 Jun 2021 18:18:41.960 # 
RAX:0000000000000000 RBX:00007fcdcf815030
RCX:000055798fd0eb80 RDX:000055798ff6fbc0
RDI:00007fcde3675eb0 RSI:0000000000000000
RBP:00007fcde3675eb0 RSP:00007fcde36753a0
R8 :0000000000000000 R9 :00007fcdcf8c22c0
R10:00000000000000eb R11:00000000000000eb
R12:0000000000000000 R13:00007fcdcf897d68
R14:00007fcde6c1f8a0 R15:0000000000000001
RIP:000055798fcbae39 EFL:0000000000010246
CSGSFS:002b000000000033
4527:M 20 Jun 2021 18:18:41.960 # (00007fcde36753af) -> 0000000000000002
4527:M 20 Jun 2021 18:18:41.960 # (00007fcde36753ae) -> 00007fcdcf8085d0
4527:M 20 Jun 2021 18:18:41.960 # (00007fcde36753ad) -> 0000000000000002
4527:M 20 Jun 2021 18:18:41.960 # (00007fcde36753ac) -> 00007fcdcf897d68
4527:M 20 Jun 2021 18:18:41.960 # (00007fcde36753ab) -> 00007fcde526bfb0
4527:M 20 Jun 2021 18:18:41.960 # (00007fcde36753aa) -> 0000000000000003
4527:M 20 Jun 2021 18:18:41.960 # (00007fcde36753a9) -> 00007fcdcf897e08
4527:M 20 Jun 2021 18:18:41.960 # (00007fcde36753a8) -> 0000000000000001
4527:M 20 Jun 2021 18:18:41.960 # (00007fcde36753a7) -> 00007fcde5268115
4527:M 20 Jun 2021 18:18:41.960 # (00007fcde36753a6) -> 00007fcde6c1f8a0
4527:M 20 Jun 2021 18:18:41.960 # (00007fcde36753a5) -> 00007fcdcf897d68
4527:M 20 Jun 2021 18:18:41.960 # (00007fcde36753a4) -> 0000000000000005
4527:M 20 Jun 2021 18:18:41.960 # (00007fcde36753a3) -> 00007fcde668c4b8
4527:M 20 Jun 2021 18:18:41.960 # (00007fcde36753a2) -> 00007fcdcf815030
4527:M 20 Jun 2021 18:18:41.960 # (00007fcde36753a1) -> 19b156a8a1a0a100
4527:M 20 Jun 2021 18:18:41.960 # (00007fcde36753a0) -> 00007fcdcf815000

------ MODULES INFO OUTPUT ------
# graph_executing commands
graph_command:GRAPH.QUERY MATCH (a)-[e*]->(b) WHERE e.connects = "CD" OR e.connects = "DE" OR e.connects = "EF" OR e.connects = "FG" RETURN a.name, b.name

------ FAST MEMORY TEST ------
4527:M 20 Jun 2021 18:18:41.961 # main thread terminated
4527:M 20 Jun 2021 18:18:41.961 # Bio thread for job type #0 terminated
4527:M 20 Jun 2021 18:18:41.961 # Bio thread for job type #1 terminated
4527:M 20 Jun 2021 18:18:41.961 # Bio thread for job type #2 terminated

Fast memory test PASSED, however your memory can still be broken. Please run a memory test for several hours if possible.

------ DUMPING CODE AROUND EIP ------
Symbol: je_large_dalloc (base: 0x55798fcbae10)
Module: redis-server *:6379 (base 0x55798fb6c000)
$ xxd -r -p /tmp/dump.hex /tmp/dump.bin
$ objdump --adjust-vma=0x55798fcbae10 -D -b binary -m i386:x86-64 /tmp/dump.bin
------
4527:M 20 Jun 2021 18:18:41.961 # dump of function (hexdump of 169 bytes):
41564155488d15a54d2b004154554989f4534889fd4883ec1064488b042528000000488944240831c0488b0625ff0f0000488b1cc28b0db54c2b00488bb310680000390e0f8396000000803dc6d32900000f850a0100004c89e24889de4889efe8cb50fcff4889e24c89e14889de4889ef48c7042400000000e8e24cfcff4885ed743c488b8db80100004c8ba3106800004885c9418b34240f84120100003b75040f830901000089f2

=== REDIS BUG REPORT END. Make sure to include from START to END. ===

       Please report the crash by opening an issue on github:

           http://github.com/redis/redis/issues

  Suspect RAM error? Use redis-server --test-memory to verify it.

```

### PR DESCRIPTION
**Pull request by jeffreylovitz**
Extensive local testing suggests that this PR resolves #1785.

It appears that `GxB_set` or the particular matrix access it performs is not thread-safe, and can cause crashes when multiple new tuple iterators all attempt to set this field on the same matrix simultaneously.

This crash seemingly can only occur on the earliest set calls to `GxB_set`.

### CODE REVIEW

File: deps/GraphBLAS/Source/GxB_Matrix_tuple_iter.c [hunk 1]
```diff
@@ -22,9 +22,6 @@ GrB_Info GxB_MatrixTupleIter_new
 	GB_WHERE(A, "GxB_MatrixTupleIter_new (A)") ;
 	GB_RETURN_IF_NULL_OR_FAULTY(A) ;
 
-	// make sure matrix is not bitmap or full
-	GxB_set(A, GxB_SPARSITY_CONTROL, GxB_SPARSE) ;
-
```
Comment (swilly22) [inline deps/GraphBLAS/Source/GxB_Matrix_tuple_iter.c:27]: Our tuple iterator can only work with SPARSE matrices, in case the matrix format isn't sparse, e.g. bitmap or full the iterator would break,
if I'm not mistaken we use our tuple iterator to iterate over two type of matrices:
1. Graph built-in matrices e.g. label/relationship matrices
2. matrices created as part of a traversal e.g. M = f*A*B

For the first case we can assure the matrices are sparse, for the second, we'll have to call `GxB_set(M, GxB_SPARSITY_CONTROL, GxB_SPARSE) ;` prior to iterating.

I feel like the issue we've encountered is iterating over a built-in matrix, multiple threads creating an iterator over the same matrix all at once.

**Review by swilly22 — CHANGES_REQUESTED** [review]
Good catch, please see comment.

File: deps/GraphBLAS/Source/GxB_Matrix_tuple_iter.c (hunk 1 above)
Comment (swilly22) [reply deps/GraphBLAS/Source/GxB_Matrix_tuple_iter.c:27]: In which case we should change this `GxB_set` to assert on the input matrix format,
in addition to `op_conditional_traverse` there are other areas in the code which are using the iterator e.g. `var_len_traversal`
this entire requirement is soon to be lifted by @OfirMos work on supporting the hyper-sparse format,

**Review by swilly22 — APPROVED** [review]
