### PR TITLE
Fix type mismatch error message

### LINKED ISSUE #2681: Incorrect error message on invalid function argument type
Just two examples:

```
GRAPH.QUERY g "RETURN isEmpty(1)"
(error) Type mismatch: expected String but was Integer
```

Expected error message:
```
(error) Type mismatch: expected List, Map, String, or Null but was Integer
```

```
GRAPH.QUERY g "RETURN toBoolean(1.5)"
(error) Type mismatch: expected String but was Float
```

Expected error message:
```
(error) Type mismatch: expected Boolean, Integer, String, or Null but was Float
```

### PR DESCRIPTION
**Pull request by nafraf**
Hi, this PR is to fix #2681 
A new function SIType_ToMultipleTypeString() was created to return the names of all the possible types.
Comments are welcome, thanks.

### CODE REVIEW

File: src/value.c [hunk 1]
```diff
@@ -259,6 +273,36 @@ const char *SIType_ToString(SIType t) {
...
+		*bufferLen += 256;
+		*buf = rm_realloc(*buf, sizeof(char) * *bufferLen);
+	}
+	// Iterate over the possible SITypes
+	for(int i = 0; i < 18; i ++) {
+		currentType = (1 << i);
+		if(t & currentType) {
+			if(t == remainingTypes) {
+				remainingTypes &= (~currentType);
+			}
```
Comment (AviAvni) [inline src/value.c:291]: what is this?

**Review by AviAvni — CHANGES_REQUESTED** [review]

File: tests/flow/test_list.py [hunk 2]
```diff
@@ -180,23 +180,23 @@ def test04_head_function(self):
             actual_result = redis_graph.query(query)
             self.env.assertTrue(False)
         except ResponseError as e:
-            self.env.assertContains("Type mismatch: expected List but was Integer", str(e))
+            self.env.assertContains("Type mismatch: expected List, or Null but was Integer", str(e))
```
Comment (AviAvni) [inline tests/flow/test_list.py:183]: last ','  need to be omitted

Comment (LiorKogan) [reply tests/flow/test_list.py:183]: If there are two items, the last comma should be omitted.
If there are more than two, the last comma should be present (US grammar conversion)
https://www.grammar-monster.com/lessons/commas_in_lists.htm

File: src/value.c (hunk 1 above)
Comment (nafraf) [reply src/value.c]: It was to detect the first type detected, now the code was changed to count the number of types detected.

File: tests/flow/test_list.py (hunk 2 above)
Comment (nafraf) [reply tests/flow/test_list.py]: Ok, change done to follow the US grammar convention. [f55591f](https://github.com/RedisGraph/RedisGraph/pull/2691/commits/f55591f8e396620eb2d18eec6a0c2be676f92b87)

File: src/value.c [hunk 3]
```diff
@@ -250,6 +252,18 @@ const char *SIType_ToString(SIType t) {
...
+	} else if(t & T_LOCALDATETIME) {
+		return "Local Datetime";
+	} else if(t & T_DATE) {
+		return "Date";
+	} else if(t & T_TIME) {
+		return "Time";
+	} else if(t & T_LOCALTIME) {
+		return "Local Time";
+	} else if(t & T_DURATION) {
+		return "Duration";
```
[the remark this answers is not in the document]
Comment (nafraf) [reply src/value.c]: Ok. Types removed in [beb887f](https://github.com/RedisGraph/RedisGraph/pull/2691/commits/beb887fe5f5a9d4d04d98200a11618ba8bf3c770)

File: src/errors.c [hunk 4]
```diff
@@ -133,8 +133,14 @@ void Error_InvalidFilterPlacement(rax *entitiesRax) {
 }
 
 void Error_SITypeMismatch(SIValue received, SIType expected) {
-	ErrorCtx_SetError("Type mismatch: expected %s but was %s", SIType_ToString(expected),
+	char *buf = rm_malloc(256 * sizeof(char));
```
Comment (swilly22) [inline src/errors.c:136]: If we believe `buf` can't grow beyond 1024 bytes let's allocate it on the stack, and modify `SIType_ToMultipleTypeString` to not perform any reallocations, probably returning early if the buffer too small (which shouldn't happen) maybe `ASSERT` in such case.

**Review by swilly22 — CHANGES_REQUESTED** [review]

File: src/value.h [hunk 5]
```diff
@@ -153,7 +153,12 @@ bool SIValue_IsTrue(SIValue v);
 
 const char *SIType_ToString(SIType t);
 
-// Prints an SIValue to a given buffer, with length (bufferLen), sets bytesWritten to the actuall length
+// Prints the SIType_ToString(), separated by comma, of all the possible types that matches with SIType t
```
[the remark this answers is not in the document]
Comment (nafraf) [reply src/value.h]: Thanks. The comments were modified. [ccc4ce0](https://github.com/RedisGraph/RedisGraph/pull/2691/commits/ccc4ce0671c3ea9c09d3e55afea20476ad5b8f01)

File: src/value.c [hunk 6]
```diff
@@ -259,6 +261,53 @@ const char *SIType_ToString(SIType t) {
...
+	// Allocate space
+	// Worst case: Len(SIType names) + 19*Len(", ") + Len("Or") = 177 + 38 + 2 = 217
+	if(*bufferLen - *bytesWritten < 256) {
+		*bufferLen += 256;
+		*buf = rm_realloc(*buf, sizeof(char) * *bufferLen);
+	}
+
+	// Remove from remainingTypes the types which are not used currently
+	remainingTypes = t & (~0x7E0);
+
```
[the remark this answers is not in the document]
Comment (nafraf) [reply src/value.c:273]: Thanks.

File: src/value.c [hunk 7]
```diff
@@ -259,6 +261,53 @@ const char *SIType_ToString(SIType t) {
...
+	uint typesDetected = 0;
+	// Iterate over the possible SITypes
+	for(int i = 0; i < 18; i ++) {
```
[the remark this answers is not in the document]
Comment (nafraf) [reply src/value.c]: Yes, now the list has only 12 items

File: src/errors.c [hunk 8]
```diff
@@ -133,8 +133,14 @@ void Error_InvalidFilterPlacement(rax *entitiesRax) {
...
+	size_t bufferLen=256;
```
[the remark this answers is not in the document]
Comment (nafraf) [reply src/errors.c]: Format fixed.

File: src/errors.c (hunk 4 above)
Comment (nafraf) [reply src/errors.c]: ASSERT() was added and reallocation was removed from ```SIType_ToMultipleTypeString ```
[44e274c](https://github.com/RedisGraph/RedisGraph/pull/2691/commits/44e274c4d072d7f04252ce0831d735fcf35d53d2)

File: src/value.c (hunk 6 above)
[the remark this answers is not in the document]
Comment (swilly22) [reply src/value.c:273]: Hi, sorry about this, but on a second thought let's keep this function generic, it shouldn't be aware about which SI_Types are actually in use and which aren't, let's take all types within the enum into consideration, there's no real harm in doing so.

**Review by swilly22 — CHANGES_REQUESTED** [review]

File: src/value.c (hunk 6 above)
[the remark this answers is not in the document]
Comment (nafraf) [reply src/value.c:279]: No problem. Change done.

1. SIType_ToString() was modified to support all types, because tostring() accepts Datetime, Duration types. Is that OK?
2. What do you think of replace:
```C
for(int i = 0; i < 18; i ++) {
    currentType = (1 << i);
 ```
By this:
```C
for(currentType = 1; currentType < SI_ALL; currentType = currentType << 1) {
```

[the remark this answers is not in the document]
Comment (swilly22) [reply src/value.c:279]: This alternative loop seems better, I don't expect it to overflow.

[the remark this answers is not in the document]
Comment (nafraf) [reply src/value.c:279]: The loop was updated. [30f2f42](https://github.com/RedisGraph/RedisGraph/pull/2691/commits/30f2f428c72572aa87fd945f293458b0f2cacb54)

File: src/value.c [hunk 9]
```diff
@@ -259,6 +273,41 @@ const char *SIType_ToString(SIType t) {
...
+void SIType_ToMultipleTypeString(SIType t, char **buf, size_t *bufferLen, size_t *bytesWritten) {
+	// Worst case: Len(SIType names) + 19*Len(", ") + Len("Or") = 177 + 38 + 2 = 217
+	ASSERT((*bufferLen - *bytesWritten) >= 256);
+
+	SIType currentType;
+	SIType remainingTypes = t;
+	
+	uint typesDetected = 0;
+	// Iterate over the possible SITypes
+	for(currentType = 1; currentType < SI_ALL; currentType = currentType << 1) {
```
Comment (swilly22) [inline src/value.c:285]: Please look into `popcount` which should return the number of active bits in an integer.

File: src/value.c [hunk 10]
```diff
@@ -259,6 +273,41 @@ const char *SIType_ToString(SIType t) {
...
+						*bytesWritten += snprintf(*buf + *bytesWritten, *bufferLen, ", or ");
+					}
+				}
+			}
+			*bytesWritten += snprintf(*buf + *bytesWritten, *bufferLen, "%s", SIType_ToString(currentType));
+			typesDetected++;
+		}
+		if(!remainingTypes) {
+			break;
+		}
```
Comment (swilly22) [inline src/value.c:307]: using `popcount` this condition should be removed.

File: src/errors.c [hunk 11]
```diff
@@ -133,8 +133,14 @@ void Error_InvalidFilterPlacement(rax *entitiesRax) {
...
 void Error_SITypeMismatch(SIValue received, SIType expected) {
-	ErrorCtx_SetError("Type mismatch: expected %s but was %s", SIType_ToString(expected),
+	size_t bufferLen = 256;
+	size_t bytesWritten = 0;
+	char *buf = rm_malloc(bufferLen * sizeof(char));
+
+	SIType_ToMultipleTypeString(expected, &buf, &bufferLen, &bytesWritten);
+	ErrorCtx_SetError("Type mismatch: expected %s but was %s", buf,
 					  SIType_ToString(SI_TYPE(received)));
+	rm_free(buf);
```
Comment (swilly22) [inline src/errors.c:143]: Please see if we can switch to a stack allocated buffer and remove all `realloc` checks within `SIType_ToMultipleTypeString`

**Review by swilly22 — CHANGES_REQUESTED** [review]

File: src/errors.c (hunk 11 above)
Comment (nafraf) [reply src/errors.c]: Change done [c87aa26](https://github.com/RedisGraph/RedisGraph/pull/2691/commits/c87aa2674d53357ce2cfc235e9e282f48382c362).
```bufferLen``` and ```bytesWritten``` are still used in ```SIType_ToMultipleTypeString``` to check the size of input buffer.  
Is it right?  Thanks

File: src/errors.c [hunk 12]
```diff
@@ -141,12 +141,11 @@ void Error_InvalidFilterPlacement(rax *entitiesRax) {
 void Error_SITypeMismatch(SIValue received, SIType expected) {
 	size_t bufferLen = 256;
 	size_t bytesWritten = 0;
-	char *buf = rm_malloc(bufferLen * sizeof(char));
+	char buf[256];
```
Comment (vityafx) [inline src/errors.c:144]: Why not just this?
```c
char buf[bufferLen];
```
Or better yet, perhaps we could remove the `size_t bufferLen = 256;` and define a named constant as this magic number is used everywhere within the file?

Comment (nafraf) [reply src/errors.c]: Thanks. I made changes to use a named constant.

File: src/errors.c (hunk 11 above)
Comment (nafraf) [reply src/errors.c]: bytesWritten argument was removed.

File: src/value.c (hunk 9 above)
Comment (nafraf) [reply src/value.c]: __builtin_popcount() is used now. The for() was replaced by while()

File: src/value.c (hunk 10 above)
Comment (nafraf) [reply src/value.c]: Ok. Done. Thanks.

File: src/value.c (hunk 6 above)
[the remark this answers is not in the document]
Comment (nafraf) [reply src/value.c:284]: @AviAvni I think your code is more readable.
The second loop needs to check ```if (t & currentType == 0)```, change was added in [f4c0207](https://github.com/RedisGraph/RedisGraph/pull/2691/commits/f4c0207bfce62a3acdfd718325bbac836807d583)

File: src/errors.c (hunk 12 above)
Comment (vityafx) [reply src/errors.c]: Great, thanks!
