### PR TITLE
clone cached record before mergeing

### LINKED ISSUE #1124: wrong output on hashjoins
```
127.0.0.1:6379> graph.query g "CREATE ({val:1}), ({val:2}), ({val:3}),({val:4})"
1) 1) "Nodes created: 4"
   2) "Properties set: 4"
   3) "Query internal execution time: 3.568600 milliseconds"
127.0.0.1:6379> graph.query g "MATCH (a {val:1}), (b), (c) WHERE a.val = b.val-1 AND b.val = c.val-1 RETURN a.val, b.val, c.val "
1) 1) "a.val"
   2) "b.val"
   3) "c.val"
2) 1) 1) (integer) 1
      2) (integer) 2
      3) (integer) 3
   2) 1) (integer) 1
      2) (integer) 3
      3) (integer) 4
3) 1) "Query internal execution time: 1.015300 milliseconds"
127.0.0.1:6379> graph.explain g "MATCH (a {val:1}), (b), (c) WHERE a.val = b.val-1 AND b.val = c.val-1 RETURN a.val, b.val, c.val "
1) "Results"
2) "    Project"
3) "        Value Hash Join | a.val = b.val - 1"
4) "            Filter"
5) "                All Node Scan | (a)"
6) "            Value Hash Join | b.val = c.val - 1"
7) "                All Node Scan | (b)"
8) "                All Node Scan | (c)"
```

### PR DESCRIPTION
**Pull request by swilly22**
Fix #1124 
I believe Record merge is dangerous, there's no validation on the record length, also what if the records have different mapping?

### CODE REVIEW

File: src/execution_plan/ops/op_value_hash_join.c [hunk 1]
```diff
@@ -32,33 +32,54 @@ static bool _record_islt(Record l, Record r, uint idx) {
...
-	int64_t left = 0;
-	int64_t right = recordCount;
+static bool _binarySearchLeftmost(int64_t *idx, Record *array, int join_key_idx, SIValue v) {
+	assert(idx != NULL);
+
+	SIValue  x;
+	int64_t  len    =  array_len(array);
+	int64_t  pos    =  0;
+	int64_t  left   =  0;
+	int64_t  right  =  len;
```
Comment (DvirDukhan) [inline src/execution_plan/ops/op_value_hash_join.c:42]: format

File: src/execution_plan/ops/op_value_hash_join.c [hunk 2]
```diff
@@ -32,33 +32,54 @@ static bool _record_islt(Record l, Record r, uint idx) {
...
 									  SIValue v) {
-	int64_t pos;
-	int64_t left = 0;
-	int64_t right = array_len;
+	assert(idx != NULL);
+
+	SIValue  x;
+	int64_t  pos    =  0;
+	int64_t  left   =  0;
+	int64_t  right  =  array_len;
```
Comment (DvirDukhan) [inline src/execution_plan/ops/op_value_hash_join.c:72]: format

**Comment by jeffreylovitz** [comment]
> Fix #1124
> I believe Record merge is dangerous, there's no validation on the record length, also what if the records have different mapping?

The 2 inputs to `Record_Merge` are not allowed to belong to different mappings (and thus always have the same length). I just tested adding an assertion to this effect, and it was not triggered by the test suite - perhaps we should add it permanently.

File: src/execution_plan/record.c [hunk 3]
```diff
@@ -67,9 +67,10 @@ void Record_Clone(const Record r, Record clone) {
 }
 
 void Record_Merge(Record *a, const Record b) {
-	uint len = Record_length(b);
+	assert((*a)->owner == b->owner);
+	uint len = Record_length(*a);
 	for(uint i = 0; i < len; i++) {
-		if(b->entries[i].type != REC_TYPE_UNKNOWN) {
+		if((*a)->entries[i].type == REC_TYPE_UNKNOWN) {
 			(*a)->entries[i] = b->entries[i];
```
Comment (jeffreylovitz) [inline src/execution_plan/record.c:74]: I don't think this is a safe assignment if any entry is a heap allocation. If `REC_TYPE_SCALAR`, we should probably transfer the value using an interface like `SI_ShareValue`.

Comment (jeffreylovitz) [reply src/execution_plan/record.c:74]: Oh, never mind - this is unnecessary because `Record_Clone` marks all such entries as volatile.

File: src/execution_plan/ops/op_value_hash_join.c (hunk 1 above)
Comment (jeffreylovitz) [reply src/execution_plan/ops/op_value_hash_join.c:42]: I second this request!

File: src/execution_plan/ops/op_value_hash_join.c (hunk 2 above)
Comment (jeffreylovitz) [reply src/execution_plan/ops/op_value_hash_join.c:72]: I second this request!

File: src/execution_plan/ops/op_value_hash_join.c [hunk 4]
```diff
@@ -32,33 +32,54 @@ static bool _record_islt(Record l, Record r, uint idx) {
...
+	// Make sure value was found.
+	*idx = left;
+	int disjointOrNull = 0;
+
+	if(left == len) return false;
+
+	x = Record_Get(array[*idx], join_key_idx);
+	// Return false if the value wasn't found or evaluated to NULL.
+	return (SIValue_Compare(x, v, &disjointOrNull) == 0 &&
+			disjointOrNull != COMPARED_NULL);
```
Comment (jeffreylovitz) [inline src/execution_plan/ops/op_value_hash_join.c:60]: One-liner.

File: src/execution_plan/ops/op_value_hash_join.c [hunk 5]
```diff
@@ -32,33 +32,54 @@ static bool _record_islt(Record l, Record r, uint idx) {
...
-		SIValue x = Record_Get(array[pos], join_key_idx);
+		x = Record_Get(array[pos], join_key_idx);
 		if(SIValue_Compare(x, v, NULL) < 0) left = pos + 1;
 		else right = pos;
 	}
-	return left;
+
+	// Make sure value was found.
+	*idx = left;
+	int disjointOrNull = 0;
```
Comment (jeffreylovitz) [inline src/execution_plan/ops/op_value_hash_join.c:53]: Move to above `SIValue_Compare` call (58).

File: src/execution_plan/ops/op_value_hash_join.c [hunk 6]
```diff
@@ -84,15 +105,11 @@ static bool _set_intersection_idx(OpValueHashJoin *op, SIValue v) {
...
+	int64_t rightmost_idx = 0;
 
-	// Make sure value was found.
-	Record r = op->cached_records[leftmost_idx];
-	SIValue x = Record_Get(r, op->join_value_rec_idx);
-	int disjointOrNull = 0;
-	// Return false if the value wasn't found or evaluated to NULL.
-	if(SIValue_Compare(x, v, &disjointOrNull) != 0 || disjointOrNull == COMPARED_NULL) return false;
+	if(!_binarySearchLeftmost(&leftmost_idx, op->cached_records,
+							  op->join_value_rec_idx, v)) return false;
```
Comment (jeffreylovitz) [inline src/execution_plan/ops/op_value_hash_join.c:112]: `return false` alone on second line.

File: src/execution_plan/ops/op_value_hash_join.c [hunk 7]
```diff
@@ -32,33 +32,54 @@ static bool _record_islt(Record l, Record r, uint idx) {
 #define RECORD_SORT_ON_ENTRY(a, b) (_record_islt((*a), (*b), idx))
 
 // Performs binary search, returns the leftmost index of a match.
-static int64_t _binarySearchLeftmost(Record *array, int join_key_idx, SIValue v) {
-	int64_t recordCount = array_len(array);
-	int64_t pos;
-	int64_t left = 0;
-	int64_t right = recordCount;
+static bool _binarySearchLeftmost(int64_t *idx, Record *array, int join_key_idx, SIValue v) {
```
Comment (jeffreylovitz) [inline src/execution_plan/ops/op_value_hash_join.c:35]: I think this signature should accept `array_len` just for consistency with `Rightmost`.

File: src/execution_plan/ops/op_value_hash_join.c [hunk 8]
```diff
@@ -32,33 +32,54 @@ static bool _record_islt(Record l, Record r, uint idx) {
...
 }
 
 // Performs binary search, returns the rightmost index of a match.
-static int64_t _binarySearchRightmost(Record *array, int64_t array_len, int join_key_idx,
-									  SIValue v) {
-	int64_t pos;
-	int64_t left = 0;
-	int64_t right = array_len;
+// assuming 'v' exists in 'array'
+static bool _binarySearchRightmost(int64_t *idx, Record *array, int64_t array_len, int join_key_idx,
```
Comment (jeffreylovitz) [inline src/execution_plan/ops/op_value_hash_join.c:65]: `uint` or `uint32_t`

File: src/execution_plan/ops/op_value_hash_join.c [hunk 9]
```diff
@@ -84,15 +105,11 @@ static bool _set_intersection_idx(OpValueHashJoin *op, SIValue v) {
 	op->number_of_intersections = 0;
 	uint record_count = array_len(op->cached_records);
 
-	int64_t leftmost_idx = _binarySearchLeftmost(op->cached_records, op->join_value_rec_idx, v);
-	if(leftmost_idx >= record_count) return false;
+	int64_t leftmost_idx = 0;
+	int64_t rightmost_idx = 0;
```
Comment (jeffreylovitz) [inline src/execution_plan/ops/op_value_hash_join.c:109]: `uint` or `uint32_t`

File: src/execution_plan/ops/op_value_hash_join.c [hunk 10]
```diff
@@ -32,33 +32,54 @@ static bool _record_islt(Record l, Record r, uint idx) {
...
-	int64_t right = array_len;
+// assuming 'v' exists in 'array'
+static bool _binarySearchRightmost(int64_t *idx, Record *array, int64_t array_len, int join_key_idx,
+								   SIValue v) {
+	assert(idx != NULL);
+
+	SIValue  x;
+	int64_t  pos    =  0;
+	int64_t  left   =  0;
+	int64_t  right  =  array_len;
```
Comment (jeffreylovitz) [inline src/execution_plan/ops/op_value_hash_join.c:72]: `uint` or `uint32_t`

File: src/execution_plan/ops/op_value_hash_join.c (hunk 1 above)
Comment (jeffreylovitz) [inline src/execution_plan/ops/op_value_hash_join.c:42]: `uint` or `uint32_t`
