### PR TITLE
Emit validation error when an alias refers to both nodes and edges

### LINKED ISSUE #590: Wrong resultset when alias is reused for both a node and a relationship.
Command: `docker run -p 6379:6379 -it --rm redislabs/redisgraph:edge`

Using the `demo/social` dataset.

The following query returns the right response.

```
127.0.0.1:6379> GRAPH.QUERY social "MATCH (n)-[n]->(m) RETURN n, m LIMIT 1"
1) 1) "n"
   2) "m"
2) 1) 1) 1) 1) "id"
            2) (integer) 0
         2) 1) "type"
            2) "visited"
         3) 1) "src_node"
            2) (integer) 13
         4) 1) "dest_node"
            2) (integer) 0
         5) 1) "properties"
            2) 1) 1) "purpose"
                  2) "business"
      2) 1) 1) "id"
            2) (integer) 0
         2) 1) "labels"
            2) 1) "country"
         3) 1) "properties"
            2) 1) 1) "name"
                  2) "USA"
3) 1) "Query internal execution time: 1.320438 milliseconds"
```

Destination node of the 1st result is returned in the place of edge data with edge properties in the 2nd result. 

```
127.0.0.1:6379> GRAPH.QUERY social "MATCH (n)-[n]->(m) RETURN n, m LIMIT 2"
1) 1) "n"
   2) "m"
2) 1) 1) 1) 1) "id"
            2) (integer) 0
         2) 1) "type"
            2) "visited"
         3) 1) "src_node"
            2) (integer) 13
         4) 1) "dest_node"
            2) (integer) 0
         5) 1) "properties"
            2) 1) 1) "purpose"
                  2) "business"
      2) 1) 1) "id"
            2) (integer) 0
         2) 1) "labels"
            2) 1) "country"
         3) 1) "properties"
            2) 1) 1) "name"
                  2) "USA"
   2) 1) 1) 1) "id"
            2) (integer) 0
         2) 1) "labels"
            2) 1) "country"
         3) 1) "properties"
            2) 1) 1) "purpose"
                  2) "business"
      2) 1) 1) "id"
            2) (integer) 1
         2) 1) "labels"
            2) 1) "country"
         3) 1) "properties"
            2) 1) 1) "name"
                  2) "Prague"
3) 1) "Query internal execution time: 0.933773 milliseconds"
```

But if we skip the destination node (`id(m) == 0`), it works fine.

```
127.0.0.1:6379> GRAPH.QUERY social "MATCH (n)-[n]->(m) WHERE id(m) > 0 RETURN n, m LIMIT 1"
1) 1) "n"
   2) "m"
2) 1) 1) 1) 1) "id"
            2) (integer) 2
         2) 1) "type"
            2) "visited"
         3) 1) "src_node"
            2) (integer) 13
         4) 1) "dest_node"
            2) (integer) 1
         5) 1) "properties"
            2) 1) 1) "purpose"
                  2) "pleasure"
      2) 1) 1) "id"
            2) (integer) 1
         2) 1) "labels"
            2) 1) "country"
         3) 1) "properties"
            2) 1) 1) "name"
                  2) "Prague"
3) 1) "Query internal execution time: 1.318126 milliseconds"
127.0.0.1:6379> GRAPH.QUERY social "MATCH (n)-[n]->(m) WHERE id(m) > 0 RETURN n, m LIMIT 2"
1) 1) "n"
   2) "m"
2) 1) 1) 1) 1) "id"
            2) (integer) 2
         2) 1) "type"
            2) "visited"
         3) 1) "src_node"
            2) (integer) 13
         4) 1) "dest_node"
            2) (integer) 1
         5) 1) "properties"
            2) 1) 1) "purpose"
                  2) "pleasure"
      2) 1) 1) "id"
            2) (integer) 1
         2) 1) "labels"
            2) 1) "country"
         3) 1) "properties"
            2) 1) 1) "name"
                  2) "Prague"
   2) 1) 1) 1) "id"
            2) (integer) 1
         2) 1) "type"
            2) "visited"
         3) 1) "src_node"
            2) (integer) 13
         4) 1) "dest_node"
            2) (integer) 1
         5) 1) "properties"
            2) 1) 1) "purpose"
                  2) "business"
      2) 1) 1) "id"
            2) (integer) 1
         2) 1) "labels"
            2) 1) "country"
         3) 1) "properties"
            2) 1) 1) "name"
                  2) "Prague"
3) 1) "Query internal execution time: 1.201543 milliseconds"
```

Link with Issue: https://github.com/RedisGraph/RedisGraph/issues/584
> The cause for the crash is the reuse of the alias `n` for both a node and a relationship, which we should probably introduce a syntax validation to disallow.

_Originally posted by @jeffreylovitz in https://github.com/RedisGraph/RedisGraph/issues/584#issuecomment-520167483_

I think it's better to not allow the re-usage of the alias for both a node and a relationship and throw a syntax error.

### PR DESCRIPTION
**Pull request by jeffreylovitz**
Resolves #590

### CODE REVIEW

File: src/ast/ast_validations.c [hunk 1]
```diff
@@ -474,15 +503,74 @@ static AST_Validation _Validate_MATCH_Clauses(const AST *ast, char **reason) {
...
+	if(with_clause_count > 0) {
+		uint scope_start = 0;
+		for(uint i = 0; i < with_clause_count; i ++) {
+			uint match_end = match_start;
+			uint scope_end = query_scopes[i];
+			// Find the last MATCH clause within this scope.
+			while((match_end < match_count) && (match_indices[match_end] < scope_end)) match_end++;
+
+			// Perform validations on all MATCH clauses within this scope.
+			res = _ValidateMatchClausesInScope(ast, projections, referred_funcs, match_indices, match_start,
```
Comment (swilly22) [inline src/ast/ast_validations.c]: Wouldn't you prefer to create an AST object for each scope and simply call _ValidateClauses on it?
If the cost of creating these sub ASTs isn't great I believe this will simplify the overall logic and make the validation bit more clear. thoughts?

File: src/ast/ast.c [hunk 2]
```diff
@@ -210,6 +211,7 @@ AST *AST_Build(cypher_parse_result_t *parse_result) {
 
 AST *AST_NewSegment(AST *master_ast, uint start_offset, uint end_offset) {
 	AST *ast = rm_malloc(sizeof(AST));
+	ast->free_root = true;
```
Comment (swilly22) [inline src/ast/ast.c]: Should we Initialise entity_map?
`ast->entity_map = NULL;`

File: src/ast/ast_validations.c [hunk 3]
```diff
@@ -442,6 +442,39 @@ static AST_Validation _Validate_MATCH_Clause_Filters(const cypher_astnode_t *cla
 	return AST_VALID;
 }
 
+static AST_Validation _ValidateNodeAlias(const cypher_astnode_t *node, TrieMap *identifiers,
```
Comment (swilly22) [inline src/ast/ast_validations.c]: Consider renaming `identifiers` to reflect that we're dealing with a set of edge aliases.

File: src/ast/ast_validations.c [hunk 4]
```diff
@@ -474,11 +507,19 @@ static AST_Validation _Validate_MATCH_Clauses(const AST *ast, char **reason) {
 		AST_ReferredFunctions(match_clause, referred_funcs);
 	}
 
+	// Verify that no relation alias is also used to denote a node
+	for(uint i = 0; i < match_count; i ++) {
+		const cypher_astnode_t *match_clause = match_clauses[i];
+		res = _ValidateReusedIdentifiers(identifiers, cypher_ast_match_get_pattern(match_clause), reason);
```
Comment (swilly22) [inline src/ast/ast_validations.c]: It's a bit difficult to understand that, at this point `identifiers` contains only edge aliases.

File: src/ast/ast_validations.c [hunk 5]
```diff
@@ -1044,19 +1103,79 @@ static AST_Validation _ValidateClauses(const AST *ast, char **reason) {
...
+	AST *scoped_ast;
+	uint scope_end;
+	uint scope_start = 0;
+	for(uint i = 0; i < with_clause_count; i ++) {
+		scope_end = query_scopes[i] + 1; // Switching from index to bound, so add 1
+		// Make a sub-AST containing only the clauses in this scope
+		scoped_ast = _NewMockASTSegment(root, scope_start, scope_end);
+
+		// Perform validations
+		res = _ValidateClauses(scoped_ast, reason);
```
Comment (swilly22) [inline src/ast/ast_validations.c]: Nice!
