### PR TITLE
do not propagate transpose effect when introducing a transpose operat…

### LINKED ISSUE #1096: Redisgraph bug report from console
Hi,
Query sent:
```
redisgraphapi          |match (g1:GraphTarget)-[o1:owner_of]->(a1:Account) -[af1:friend_of]-(a2:Account)<-[o2:owner_of]-(g2:GraphTarget)
redisgraphapi          | match (a1)-[af2:friend_of]-(a3:Account)
redisgraphapi          | where 
redisgraphapi          |     af1.verified = 'true' 
redisgraphapi          |     and af2.verified = 'true' 
redisgraphapi          |     and g1.AppId = 2
redisgraphapi          | 
redisgraphapi          | return *
```
I think it is happening because `[af1:friend_of]-` is missing `>`
Error report:
```
redisgraph             | redis-server: /redisgraph/src/arithmetic/algebraic_expression/utils.c:26: _AlgebraicExpression_InplaceRepurpose: Assertion `exp && replacement && AlgebraicExpression_ChildCount(exp) == 0' failed.



redisgraph             | 
redisgraph             | 
redisgraph             | === REDIS BUG REPORT START: Cut & paste starting from here ===
redisgraph             | 1:M 12 May 2020 13:10:51.635 # Redis 6.0.0 crashed by signal: 11
redisgraph             | 1:M 12 May 2020 13:10:51.635 # Crashed running the instruction at: 0x7f6c5526d611
redisgraph             | 1:M 12 May 2020 13:10:51.635 # Accessing address: (nil)
redisgraph             | 1:M 12 May 2020 13:10:51.635 # Failed assertion: <no assertion failed> (<no file>:0)
redisgraph             | 
redisgraph             | ------ STACK TRACE ------
redisgraph             | EIP:
redisgraph             | /lib/x86_64-linux-gnu/libc.so.6(abort+0x1fd)[0x7f6c5526d611]
redisgraph             | 
redisgraph             | Backtrace:
redisgraph             | redis-server *:6379(logStackTrace+0x32)[0x558ac8f5e922]
redisgraph             | redis-server *:6379(sigsegvHandler+0x9e)[0x558ac8f5effe]
redisgraph             | /lib/x86_64-linux-gnu/libpthread.so.0(+0x12730)[0x7f6c55420730]
redisgraph             | /lib/x86_64-linux-gnu/libc.so.6(abort+0x1fd)[0x7f6c5526d611]
redisgraph             | /lib/x86_64-linux-gnu/libc.so.6(+0x2240f)[0x7f6c5526d40f]
redisgraph             | /lib/x86_64-linux-gnu/libc.so.6(+0x30102)[0x7f6c5527b102]
redisgraph             | /usr/lib/redis/modules/redisgraph.so(_AlgebraicExpression_InplaceRepurpose+0x99)[0x7f6c542f41e9]
redisgraph             | /usr/lib/redis/modules/redisgraph.so(AlgebraicExpression_Transpose+0x18f)[0x7f6c542f458f]
redisgraph             | /usr/lib/redis/modules/redisgraph.so(AlgebraicExpression_Transpose+0x101)[0x7f6c542f4501]
redisgraph             | /usr/lib/redis/modules/redisgraph.so(orderExpressions+0xabe)[0x7f6c5430a4ce]
redisgraph             | /usr/lib/redis/modules/redisgraph.so(ExecutionPlan_PopulateExecutionPlan+0x2d8)[0x7f6c542fae58]
redisgraph             | /usr/lib/redis/modules/redisgraph.so(NewExecutionPlan+0x1f5)[0x7f6c542fbcb5]
redisgraph             | /usr/lib/redis/modules/redisgraph.so(Graph_Query+0x31d)[0x7f6c542f68ad]
redisgraph             | /usr/lib/redis/modules/redisgraph.so(+0x1ec61d)[0x7f6c5432761d]
redisgraph             | /lib/x86_64-linux-gnu/libpthread.so.0(+0x7fa3)[0x7f6c55415fa3]
redisgraph             | /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7f6c553444cf]
redisgraph             | 
redisgraph             | ------ INFO OUTPUT ------
redisgraph             | # Server
redisgraph             | redis_version:6.0.0
redisgraph             | redis_git_sha1:00000000
redisgraph             | redis_git_dirty:0
redisgraph             | redis_build_id:206b049ab77cda74
redisgraph             | redis_mode:standalone
redisgraph             | os:Linux 5.3.0-1018-gcp x86_64
redisgraph             | arch_bits:64
redisgraph             | multiplexing_api:epoll
redisgraph             | atomicvar_api:atomic-builtin
redisgraph             | gcc_version:8.3.0
redisgraph             | process_id:1
redisgraph             | run_id:f5bb7355a919e07c34e3bdfe050831dae64f670c
redisgraph             | tcp_port:6379
redisgraph             | uptime_in_seconds:20
redisgraph             | uptime_in_days:0
redisgraph             | hz:10
redisgraph             | configured_hz:10
redisgraph             | lru_clock:12230747
redisgraph             | executable:/data/redis-server
redisgraph             | config_file:
redisgraph             | 
redisgraph             | # Clients
redisgraph             | connected_clients:1
redisgraph             | client_recent_max_input_buffer:2
redisgraph             | client_recent_max_output_buffer:0
redisgraph             | blocked_clients:1
redisgraph             | tracking_clients:0
redisgraph             | clients_in_timeout_table:0
redisgraph             | 
redisgraph             | # Memory
redisgraph             | used_memory:2653480
redisgraph             | used_memory_human:2.53M
redisgraph             | used_memory_rss:15011840
redisgraph             | used_memory_rss_human:14.32M
redisgraph             | used_memory_peak:2653480
redisgraph             | used_memory_peak_human:2.53M
redisgraph             | used_memory_peak_perc:101.10%
redisgraph             | used_memory_overhead:853794
redisgraph             | used_memory_startup:836736
redisgraph             | used_memory_dataset:1799686
redisgraph             | used_memory_dataset_perc:99.06%
redisgraph             | allocator_allocated:2714168
redisgraph             | allocator_active:3182592
redisgraph             | allocator_resident:6213632
redisgraph             | total_system_memory:15733825536
redisgraph             | total_system_memory_human:14.65G
redisgraph             | used_memory_lua:37888
redisgraph             | used_memory_lua_human:37.00K
redisgraph             | used_memory_scripts:0
redisgraph             | used_memory_scripts_human:0B
redisgraph             | number_of_cached_scripts:0
redisgraph             | maxmemory:0
redisgraph             | maxmemory_human:0B
redisgraph             | maxmemory_policy:noeviction
redisgraph             | allocator_frag_ratio:1.17
redisgraph             | allocator_frag_bytes:468424
redisgraph             | allocator_rss_ratio:1.95
redisgraph             | allocator_rss_bytes:3031040
redisgraph             | rss_overhead_ratio:2.42
redisgraph             | rss_overhead_bytes:8798208
redisgraph             | mem_fragmentation_ratio:5.86
redisgraph             | mem_fragmentation_bytes:12450264
redisgraph             | mem_not_counted_for_evict:0
redisgraph             | mem_replication_backlog:0
redisgraph             | mem_clients_slaves:0
redisgraph             | mem_clients_normal:16986
redisgraph             | mem_aof_buffer:0
redisgraph             | mem_allocator:jemalloc-5.1.0
redisgraph             | active_defrag_running:0
redisgraph             | lazyfree_pending_objects:0
redisgraph             | 
redisgraph             | # Persistence
redisgraph             | loading:0
redisgraph             | rdb_changes_since_last_save:11109
redisgraph             | rdb_bgsave_in_progress:0
redisgraph             | rdb_last_save_time:1589289031
redisgraph             | rdb_last_bgsave_status:ok
redisgraph             | rdb_last_bgsave_time_sec:-1
redisgraph             | rdb_current_bgsave_time_sec:-1
redisgraph             | rdb_last_cow_size:0
redisgraph             | aof_enabled:1
redisgraph             | aof_rewrite_in_progress:0
redisgraph             | aof_rewrite_scheduled:0
redisgraph             | aof_last_rewrite_time_sec:-1
redisgraph             | aof_current_rewrite_time_sec:-1
redisgraph             | aof_last_bgrewrite_status:ok
redisgraph             | aof_last_write_status:ok
redisgraph             | aof_last_cow_size:0
redisgraph             | module_fork_in_progress:0
redisgraph             | module_fork_last_cow_size:0
redisgraph             | aof_current_size:5441299
redisgraph             | aof_base_size:5441299
redisgraph             | aof_pending_rewrite:0
redisgraph             | aof_buffer_length:0
redisgraph             | aof_rewrite_buffer_length:0
redisgraph             | aof_pending_bio_fsync:0
redisgraph             | aof_delayed_fsync:0
redisgraph             | 
redisgraph             | # Stats
redisgraph             | total_connections_received:1
redisgraph             | total_commands_processed:9
redisgraph             | instantaneous_ops_per_sec:0
redisgraph             | total_net_input_bytes:431
redisgraph             | total_net_output_bytes:30646
redisgraph             | instantaneous_input_kbps:0.00
redisgraph             | instantaneous_output_kbps:0.00
redisgraph             | rejected_connections:0
redisgraph             | sync_full:0
redisgraph             | sync_partial_ok:0
redisgraph             | sync_partial_err:0
redisgraph             | expired_keys:0
redisgraph             | expired_stale_perc:0.00
redisgraph             | expired_time_cap_reached_count:0
redisgraph             | expire_cycle_cpu_milliseconds:0
redisgraph             | evicted_keys:0
redisgraph             | keyspace_hits:22218
redisgraph             | keyspace_misses:1
redisgraph             | pubsub_channels:0
redisgraph             | pubsub_patterns:0
redisgraph             | latest_fork_usec:0
redisgraph             | migrate_cached_sockets:0
redisgraph             | slave_expires_tracked_keys:0
redisgraph             | active_defrag_hits:0
redisgraph             | active_defrag_misses:0
redisgraph             | active_defrag_key_hits:0
redisgraph             | active_defrag_key_misses:0
redisgraph             | tracking_total_keys:0
redisgraph             | tracking_total_items:0
redisgraph             | unexpected_error_replies:0
redisgraph             | 
redisgraph             | # Replication
redisgraph             | role:master
redisgraph             | connected_slaves:0
redisgraph             | master_replid:d3b7de02d514073f32e94f493a3cacda4e1cd93b
redisgraph             | master_replid2:0000000000000000000000000000000000000000
redisgraph             | master_repl_offset:0
redisgraph             | master_repl_meaningful_offset:0
redisgraph             | second_repl_offset:-1
redisgraph             | repl_backlog_active:0
redisgraph             | repl_backlog_size:1048576
redisgraph             | repl_backlog_first_byte_offset:0
redisgraph             | repl_backlog_histlen:0
redisgraph             | 
redisgraph             | # CPU
redisgraph             | used_cpu_sys:0.355440
redisgraph             | used_cpu_user:9.187885
redisgraph             | used_cpu_sys_children:0.001840
redisgraph             | used_cpu_user_children:0.002941
redisgraph             | 
redisgraph             | # Modules
redisgraph             | module:name=graph,ver=20200,api=1,filters=0,usedby=[],using=[],options=[]
redisgraph             | 
redisgraph             | # Commandstats
redisgraph             | cmdstat_graph.QUERY:calls=1,usec=34,usec_per_call=34.00
redisgraph             | cmdstat_info:calls=8,usec=746,usec_per_call=93.25
redisgraph             | 
redisgraph             | # Cluster
redisgraph             | cluster_enabled:0
redisgraph             | 
redisgraph             | # Keyspace
redisgraph             | db0:keys=1,expires=0,avg_ttl=0
redisgraph             | 
redisgraph             | ------ CLIENT LIST OUTPUT ------
redisgraph             | id=5 addr=172.29.0.2:35420 fd=10 name= age=20 idle=0 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=graph.QUERY user=default
redisgraph             | 
redisgraph             | ------ REGISTERS ------
redisgraph             | 1:M 12 May 2020 13:10:51.638 # 
redisgraph             | RAX:0000000000000000 RBX:0000000000000000
redisgraph             | RCX:0000000000000000 RDX:0000000000000000
redisgraph             | RDI:0000000000000002 RSI:00007f6c54137f40
redisgraph             | RBP:00007f6c553cfee0 RSP:00007f6c54138060
redisgraph             | R8 :0000000000000000 R9 :00007f6c54137f40
redisgraph             | R10:0000000000000008 R11:0000000000000246
redisgraph             | R12:00007f6c547b0530 R13:00007f6c547b0610
redisgraph             | R14:000000000000001a R15:00007f6c4fa080fc
redisgraph             | RIP:00007f6c5526d611 EFL:0000000000010246
redisgraph             | CSGSFS:002b000000000033
redisgraph             | 1:M 12 May 2020 13:10:51.638 # (00007f6c5413806f) -> 0000000000000000
redisgraph             | 1:M 12 May 2020 13:10:51.638 # (00007f6c5413806e) -> 0000000000000000
redisgraph             | 1:M 12 May 2020 13:10:51.638 # (00007f6c5413806d) -> 0000000000000000
redisgraph             | 1:M 12 May 2020 13:10:51.638 # (00007f6c5413806c) -> 0000000000000000
redisgraph             | 1:M 12 May 2020 13:10:51.638 # (00007f6c5413806b) -> 0000000000000000
redisgraph             | 1:M 12 May 2020 13:10:51.638 # (00007f6c5413806a) -> 0000000000000000
redisgraph             | 1:M 12 May 2020 13:10:51.638 # (00007f6c54138069) -> 0000000000000000
redisgraph             | 1:M 12 May 2020 13:10:51.638 # (00007f6c54138068) -> 0000000000000000
redisgraph             | 1:M 12 May 2020 13:10:51.638 # (00007f6c54138067) -> 0000000000000000
redisgraph             | 1:M 12 May 2020 13:10:51.638 # (00007f6c54138066) -> 0000000000000000
redisgraph             | 1:M 12 May 2020 13:10:51.638 # (00007f6c54138065) -> 0000000000000000
redisgraph             | 1:M 12 May 2020 13:10:51.638 # (00007f6c54138064) -> 0000000000000000
redisgraph             | 1:M 12 May 2020 13:10:51.638 # (00007f6c54138063) -> 0000000000000000
redisgraph             | 1:M 12 May 2020 13:10:51.638 # (00007f6c54138062) -> 0000000000000000
redisgraph             | 1:M 12 May 2020 13:10:51.638 # (00007f6c54138061) -> 0000000000000000
redisgraph             | 1:M 12 May 2020 13:10:51.638 # (00007f6c54138060) -> 0000000000000020
redisgraph             | 
redisgraph             | ------ MODULES INFO OUTPUT ------
redisgraph             | 
redisgraph             | ------ FAST MEMORY TEST ------
redisgraph             | 1:M 12 May 2020 13:10:51.638 # Bio thread for job type #0 terminated
redisgraph             | 1:M 12 May 2020 13:10:51.638 # Bio thread for job type #1 terminated
redisgraph             | 1:M 12 May 2020 13:10:51.639 # Bio thread for job type #2 terminated
redisgraph             | *** Preparing to test memory region 558ac90a9000 (2277376 bytes)
redisgraph             | *** Preparing to test memory region 558aca371000 (3506176 bytes)
redisgraph             | *** Preparing to test memory region 7f6c40000000 (2146304 bytes)
redisgraph             | *** Preparing to test memory region 7f6c48000000 (135168 bytes)
redisgraph             | *** Preparing to test memory region 7f6c4f200000 (8388608 bytes)
redisgraph             | *** Preparing to test memory region 7f6c4fa00000 (4194304 bytes)
redisgraph             | *** Preparing to test memory region 7f6c4feb3000 (2621440 bytes)
redisgraph             | *** Preparing to test memory region 7f6c50134000 (8388608 bytes)
redisgraph             | *** Preparing to test memory region 7f6c50935000 (8388608 bytes)
redisgraph             | *** Preparing to test memory region 7f6c51136000 (8388608 bytes)
redisgraph             | *** Preparing to test memory region 7f6c51937000 (8388608 bytes)
redisgraph             | *** Preparing to test memory region 7f6c52138000 (8388608 bytes)
redisgraph             | *** Preparing to test memory region 7f6c52939000 (8388608 bytes)
redisgraph             | *** Preparing to test memory region 7f6c5313a000 (8388608 bytes)
redisgraph             | *** Preparing to test memory region 7f6c5393b000 (8388608 bytes)
redisgraph             | *** Preparing to test memory region 7f6c549fd000 (12288 bytes)
redisgraph             | *** Preparing to test memory region 7f6c54a00000 (8388608 bytes)
redisgraph             | *** Preparing to test memory region 7f6c55247000 (16384 bytes)
redisgraph             | *** Preparing to test memory region 7f6c55408000 (24576 bytes)
redisgraph             | *** Preparing to test memory region 7f6c5542b000 (16384 bytes)
redisgraph             | *** Preparing to test memory region 7f6c55714000 (16384 bytes)
redisgraph             | *** Preparing to test memory region 7f6c5593c000 (8192 bytes)
redisgraph             | *** Preparing to test memory region 7f6c5593f000 (4096 bytes)
redisgraph             | *** Preparing to test memory region 7f6c55969000 (4096 bytes)
redisgraphapi          | -------------------------------------------------------------
redisgraphapi          | Redis connection lost and command aborted. It might have been processed.
redisgraphapi          | -------------------------------------------------------------
redisgraph             | .O.O.O.O.O.O.O.O.O.O.O.O.O.O.proxy                  | 172.69.130.99 - - [12/May/2020:13:10:52 +0000] "POST /api/research/graph/query/ HTTP/1.1" 200 86 "https://stgsite.abcxyz.app/profile/5/contacts-new" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
redisgraph exited with code 139
```

### PR DESCRIPTION
**Pull request by swilly22**
…ion, maintain expression structure
Fixes #1096 

We used to propagate transpose effect e.g. swap operands and domains whenever we added a transpose operation to an expression, with this change transpose operation is no different from any other operation when introduce, source and destination domains of an expression are computed by traversing an expression, we would like to maintain operand domains regardless if they are transposed.

### CODE REVIEW

File: tests/unit/test_algebraic_expression.cpp [hunk 1]
```diff
@@ -341,6 +341,177 @@ TEST_F(AlgebraicExpressionTest, AlgebraicExpression_New) {
     AlgebraicExpression_Free(operation);
 }
 
+TEST_F(AlgebraicExpressionTest, AlgebraicExpression_Domains) {	
+	GrB_Matrix A;
+	GrB_Matrix B;
+    const char *src;
+    const char *dest;
```
Comment (DvirDukhan) [inline tests/unit/test_algebraic_expression.cpp:348]: Add comments about operations domains:
`The addition operation is done over matrices with the same source and destination domain`
`Multiplication source domain is the first operand row domain, and destination domain is the last operand column domain.`
`The domain names A and B represent the tuple <row domain, col domain> of the matrices A and B`
also, rename src and dest to srcDomain, destDomain

File: tests/unit/test_algebraic_expression.cpp [hunk 2]
```diff
@@ -341,6 +341,177 @@ TEST_F(AlgebraicExpressionTest, AlgebraicExpression_New) {
...
+
+    // A*B
+    // Source(A*B) = A.
+    // Destination(A*B) = B.
+    exp = AlgebraicExpression_FromString("A*B", matrices);
+    src = AlgebraicExpression_Source(exp);
+    dest = AlgebraicExpression_Destination(exp);
+    ASSERT_STREQ(src, "A");
+    ASSERT_STREQ(dest, "B");
+    AlgebraicExpression_Free(exp);
```
[the remark this answers is not in the document]
Comment (swilly22) [reply tests/unit/test_algebraic_expression.cpp:408]: 👍

File: tests/unit/test_algebraic_expression.cpp (hunk 1 above)
Comment (swilly22) [reply tests/unit/test_algebraic_expression.cpp]: 👍
