### PR TITLE
Fix Duplicate reports when matching relationship type :R|R

### LINKED ISSUE #2643: Duplicate reports when matching relationship type :R|R
RedisGraph 2.8.20

```
FLUSHALL
GRAPH.QUERY g "CREATE (a:A)-[r1:R1]->(b:B), (a)-[r:R2]->(b:B)"
```

The following query returns the expected result:
```
GRAPH.QUERY g "MATCH (a:A)-[r:R1|R2]->(b:B) RETURN r"
```

The following *invalid* query returns the same result
```
GRAPH.QUERY g "MATCH (a:A)-[r:R1|:R2]->(b:B) RETURN r"
```

Neo4j:
> The semantics of using colon in the separation of alternative relationship types in conjunction with the use of variable binding, inlined property predicates, or variable length is no longer supported.

But more troubling are the following *valid* queries:

Each relationship is reported twice:
```
GRAPH.QUERY g "MATCH (a:A)-[r:R1|R1]->(b:B) RETURN r"
```

Each relationship is reported four times:
```
GRAPH.QUERY g "MATCH (a:A)-[r:R1|R1|R1|R1]->(b:B) RETURN r"
```

Each relationship is reported twice:
```
GRAPH.QUERY g "MATCH (a:A)-[r:R1|R2|R1|R2]->(b:B) RETURN r"
```

### PR DESCRIPTION
**Pull request by nafraf**
Hi, this PR is to fix #2643

The function _QueryGraphAddEdge() was modified to prevent add duplicated ids to edge->reltypeIDs array.

Tests were added in test_graph_create.py, please check if it is the correct file to add them.

### CODE REVIEW

File: src/graph/query_graph.c [hunk 1]
```diff
@@ -88,7 +88,19 @@ static void _QueryGraphAddEdge
 			qg->unknown_reltype_ids = true;
 			continue;
 		}
-		array_append(edge->reltypeIDs, s->id);
+		// search if s-id exists in edge->reltypeIDs to don't insert duplicates ids
+		bool found = false;
```
Comment (AviAvni) [inline src/graph/query_graph.c:92]: what happen if schema is not found we add the same name twice to `edge->reltypes`
then the plan is cached and after we create the data we will have the same problem

Comment (nafraf) [reply src/graph/query_graph.c]: You are right. I made some changes to prevent duplicates when schema is not found.
