### PR TITLE
hot fixed ast validation for DELETE. fixes #639

### LINKED ISSUE #639: malformed delete query
MOD-330

### PR DESCRIPTION
**Pull request by DvirDukhan**
This PR introduces a quick fix for AST validation done over DELETE clause. The additional validation allows the DELETE to be called either after a match clause, or, after a projection. The critical part of the fix is that each delete expression is validated to be an identifier.

### CODE REVIEW

File: src/ast/ast_validations.c [hunk 1]
```diff
@@ -782,8 +782,21 @@ static AST_Validation _Validate_DELETE_Clauses(const AST *ast, char **reason) {
 	if(!delete_clause) return AST_VALID;
 
 	const cypher_astnode_t *match_clause = AST_GetClause(ast, CYPHER_AST_MATCH);
-	if(!match_clause) return AST_INVALID;
-
+	// Check for delete a projected entity such in "MATCH (n) WITH n AS x DELETE x".
+	const cypher_astnode_t *with_clause = AST_GetClause(ast, CYPHER_AST_WITH);
+	assert(!(with_clause && match_clause));
```
Comment (swilly22) [inline src/ast/ast_validations.c]: I believe this is guaranteed by segmentation and shouldn't be tested here.

File: src/ast/ast_validations.c [hunk 2]
```diff
@@ -782,8 +782,21 @@ static AST_Validation _Validate_DELETE_Clauses(const AST *ast, char **reason) {
...
+	if(!match_clause && !with_clause) return AST_INVALID;
```
Comment (swilly22) [inline src/ast/ast_validations.c]: Unfortunately I believe the following is valid:
`CREATE (a) DELETE a`
I would omit this check.

File: src/ast/ast_validations.c [hunk 3]
```diff
@@ -782,8 +782,21 @@ static AST_Validation _Validate_DELETE_Clauses(const AST *ast, char **reason) {
...
+
+	// Validate that every deleted object is an identifier and not property.
+	uint nitems = cypher_ast_delete_nexpressions(delete_clause);
+	for(uint i = 0; i < nitems; i++) {
+		const cypher_astnode_t *ast_expr = cypher_ast_delete_get_expression(delete_clause, i);
+		if(cypher_astnode_type(ast_expr) != CYPHER_AST_IDENTIFIER) {
+			asprintf(reason, "DELETE support the removal of valid graph entities only.");
```
Comment (swilly22) [inline src/ast/ast_validations.c]: Is this the same error we're getting from Neo?

File: src/ast/ast_validations.c [hunk 4]
```diff
@@ -782,8 +782,21 @@ static AST_Validation _Validate_DELETE_Clauses(const AST *ast, char **reason) {
...
+			return AST_INVALID;
+		}
+		// TODO: Validated that the deleted entities are indeed matched or projected.
```
Comment (swilly22) [inline src/ast/ast_validations.c]: Agree, let's leave this for another day.

File: src/ast/ast_validations.c (hunk 1 above)
Comment (DvirDukhan) [reply src/ast/ast_validations.c]: removed

File: src/ast/ast_validations.c (hunk 3 above)
Comment (DvirDukhan) [reply src/ast/ast_validations.c]: Neo returns runtime error when deleting something other than a graph entity. As for the compile-time exception, it only alerts when the removed expression identifier appears for the first time, in the DELETE clause.

File: src/ast/ast_validations.c (hunk 4 above)
Comment (DvirDukhan) [reply src/ast/ast_validations.c]: open issue #645
