### PR TITLE
Fix Record ID of edges held in ExpandInto op

### LINKED ISSUE #605: data missing when matching on relationship property
Hi, this looks like a bug on the face of it, but any scalable workarounds appreciated in the meantime. 

Given a graph of 'songs' which are in 'lists' which are active on a particular 'slot' on a 'system', the search for 'songs' that appear in two different 'lists' that are active on different 'slots' on a 'system' returns no results, whereas it should return the intersection.

EG, set up the data:
`graph.query test "CREATE (s:system {system_id :'SYSA'}) CREATE (l1:list {list_name : 'ALL'}) CREATE (l2:list {list_name : 'FIRST'}) CREATE (l3:list {list_name : 'LAST'}) CREATE (so1:song {song_title:'song1'}) CREATE (so2:song {song_title:'song2'}) CREATE (so3:song {song_title:'song3'}) CREATE (so4:song {song_title:'song4'}) CREATE (so1)-[i1:IN]->(l1) CREATE (so2)-[i2:IN]->(l1) CREATE (so3)-[i3:IN]->(l1) CREATE (so4)-[i4:IN]->(l1) CREATE (so1)-[i5:IN]->(l2) CREATE (so2)-[i6:IN]->(l2) CREATE (so3)-[i7:IN]->(l3) CREATE (so4)-[i8:IN]->(l3) CREATE (l1)-[ls1:LS {slot :1}]->(s) CREATE (l2)-[ls2:LS {slot :2}]->(s) CREATE (l3)-[ls3:LS {slot :3}]->(s)"`

Run the query to get the songs within lists that are active on particular slots within the system:

`graph.query test "MATCH (sys:system) WHERE sys.system_id = 'SYSA' MATCH (li1:list)-[ls:LS]->(sys) WHERE ls.slot = 1 MATCH (li2:list)-[ls2:LS]->(sys) WHERE ls2.slot = 2 MATCH (so:song)-[:IN]->(li1) MATCH (so:song)-[:IN]->(li2) RETURN so;"`

Note nil results. (this is the bug)

Observe the songs are returned correctly when referencing the lists by their 'list_name' property directly, rather than the 'slot' from the system-list relationship. : 

`graph.query test "MATCH (li1:list) WHERE li1.list_name = 'ALL' MATCH (li2:list) WHERE li2.list_name = 'FIRST' MATCH (so:song)-[:IN]->(li1) MATCH (so:song)-[:IN]->(li2) RETURN so;"`

Observe that the lists themselves are returned correctly when referenced by slot:

`graph.query test "MATCH (sys:system) WHERE sys.system_id = 'SYSA' MATCH (li1:list)-[ls:LS]->(sys) WHERE ls.slot = 1 MATCH (li2:list)-[ls2:LS]->(sys) WHERE ls2.slot = 2 RETURN li1, li2;"`

Observe songs are returned correctly when referencing a single list by a slot:

`graph.query test "MATCH (sys:system) WHERE sys.system_id = 'SYSA' MATCH (li1:list)-[ls:LS]->(sys) WHERE ls.slot = 1 MATCH (so:song)-[:IN]->(li1) RETURN so;`

Cheers,
Rene

### PR DESCRIPTION
**Pull request by jeffreylovitz**
Resolves #605 

Most of the changes in this PR just make `NewExpandIntoOp` more similar to `NewCondTraverseOp`.

The only important line is `op_expand_into.c:109`, which corrects a mis-assignment of the Record ID of ExpandInto's contained edge. The new logic is the same logic as seen in `NewCondTraverseOp`.

### CODE REVIEW

File: src/execution_plan/ops/op_expand_into.c [hunk 1]
```diff
@@ -114,7 +106,7 @@ OpBase *NewExpandIntoOp(AlgebraicExpression *ae, RecordMap *record_map, uint rec
 	expandInto->op.modifies = NULL;
 
 	if(ae->edge) {
-		expandInto->edgeIdx = ae->edge->id;
+		expandInto->edgeIdx = RecordMap_FindOrAddID(record_map, ae->edge->id);
```
Comment (jeffreylovitz) [inline src/execution_plan/ops/op_expand_into.c]: This is the actual fix.
