### PR TITLE
Set all properties

### LINKED ISSUE #1551: Regression in SET property map logic
As the map datatype has been introduced, but handling for map updates has not, the following query and a number of its variants currently cause server crashes:
```
MATCH (a) SET a += {prop: 5}
```

### PR DESCRIPTION
**Pull request by jeffreylovitz**
Adds support for updating entities with maps using the syntax:
```
MATCH (a) SET a = {v: 1, v2: 2}
MATCH (a) SET a += {v: 1, v2: 2}
```

Also fixes a bug in which NULL-setting indexed values on single-property indexes does not correctly delete the entity from the index.

Resolves #1551 and #943.

### CODE REVIEW

File: src/execution_plan/ops/shared/update_functions.c [hunk 1]
```diff
@@ -0,0 +1,147 @@
...
+
+	// Make sure we're updating either a node or an edge.
+	if(t != REC_TYPE_NODE && t != REC_TYPE_EDGE) {
+		ErrorCtx_RaiseRuntimeException("Update error: alias '%s' did not resolve to a graph entity",
+									   alias);
+	}
+
+	GraphEntity *entity = Record_GetGraphEntity(r, ctx->record_idx);
+
+	if(t == REC_TYPE_NODE) node_update = true;
```
Comment (swilly22) [inline src/execution_plan/ops/shared/update_functions.c:85]: `node_update = t == REC_TYPE_NODE;

File: src/execution_plan/ops/shared/update_functions.c [hunk 2]
```diff
@@ -0,0 +1,147 @@
...
+	}
+
+	// If this update replaces all existing properties, enqueue an update to do so.
+	if(ctx->mode == UPDATE_REPLACE) {
+		PendingUpdateCtx update = {
+			.ge            =  entity,
+			.label_id      =  label_id,
+			.update_index  = (label_id != GRAPH_NO_LABEL),
+			.attr_id       =  ATTRIBUTE_ALL,
+		};
```
Comment (swilly22) [inline src/execution_plan/ops/shared/update_functions.c:109]: What is the meaning of this pending update?
is it suppose to clear all attributes of the entity ?

File: src/execution_plan/ops/shared/update_functions.c [hunk 3]
```diff
@@ -0,0 +1,147 @@
...
+		*updates = array_append(*updates, update);
+	}
+
+	uint exp_count = array_len(ctx->properties);
+	for(uint i = 0; i < exp_count; i++) {
+		bool update_index = false;
+		SIValue new_value = AR_EXP_Evaluate(ctx->properties[i].value, r);
```
Comment (swilly22) [inline src/execution_plan/ops/shared/update_functions.c:116]: Just to make things a bit clearer: `PropertySetCtx property = ctx->properties[i];`

File: src/execution_plan/ops/shared/update_functions.c [hunk 4]
```diff
@@ -0,0 +1,147 @@
...
+		if(node_update && label_id != GRAPH_NO_LABEL) {
+			// If the (label:attribute) combination has an index, take note.
+			update_index = GraphContext_GetIndex(gc, label, &attr_id, IDX_ANY) != NULL;
+		}
+
+		PendingUpdateCtx update = {
+			.ge            =  entity,
+			.label_id      =  label_id,
+			.new_value     =  new_value,
+			.update_index  =  update_index,
```
Comment (swilly22) [inline src/execution_plan/ops/shared/update_functions.c:139]: This `update` describes a single update to an entity, make sure that if a specific entity has a number of attributes updated say `SET n.a = 1, n.b = 1` where both `a` and `b` are indexed fields then `n` must be re-indexed only once, otherwise this will hurt performance.

File: src/execution_plan/ops/shared/update_functions.c [hunk 5]
```diff
@@ -0,0 +1,147 @@
...
+		// Retrieve the node's local label if present.
+		label = NODE_GET_LABEL(n);
+		// Retrieve the node's Label ID from a local member or the graph.
+		label_id = NODE_GET_LABEL_ID(n, gc->g);
+		if((label == NULL) && (label_id != GRAPH_NO_LABEL)) {
+			// Label ID has been found but its name is unknown, retrieve its name and update the node.
+			s = GraphContext_GetSchemaByID(gc, label_id, SCHEMA_NODE);
+			label = Schema_GetName(s);
+			n->label = label;
+		}
```
Comment (swilly22) [inline src/execution_plan/ops/shared/update_functions.c:99]: let's try working solely with `label_id`

File: src/execution_plan/ops/shared/update_functions.c [hunk 6]
```diff
@@ -0,0 +1,147 @@
...
+		PendingUpdateCtx *update = updates + i;
+		// Update the property on the graph entity.
+		properties_set += _UpdateEntity(update);
+
+		// Update index for node entities if indexed fields have been modified.
+		if(update->update_index) {
+			Schema *s = GraphContext_GetSchemaByID(gc, update->label_id, SCHEMA_NODE);
+			// Introduce updated entity to index.
+			Schema_AddNodeToIndices(s, (Node *)update->ge);
+		}
```
Comment (swilly22) [inline src/execution_plan/ops/shared/update_functions.c:59]:
```
CREATE INDEX ON :Person(age)
CREATE INDEX ON :Person(name)
MATCH (p:Person) SET p.age = 33, p.name = 'Alex'
```

Update query updates both indexed fields, but we should call `Schema_AddNodeToIndices` only once to re-index the entity, otherwise there will be a performance hit.

this might be a simple fix, checking if we need to update the index within the loop, but performing the test and calling reindexing outside of the loop:

```
bool reindex = false;
for(uint i = 0; i < update_count; i++) {
    ...
    reindex |= update->update_index;
}

if(reindex) ...
```

**Review by swilly22 — CHANGES_REQUESTED** [review]
done reviewing

**Review by swilly22 — APPROVED** [review]
